version: '3.7'
services:
  db-sql:
    container_name: sql-server
    hostname: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Mi_Super_Mega_Clave_Sql_Server"
      ACCEPT_EULA: "Y"
    volumes:
      - C:/Users/Ema/Desktop/Cursos/SQL_Server_Docker/Files/01 Sql Server:/scripts
    restart: always
  db-no-sql:
    container_name: mongo
    hostname: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "Mi_Super_Mega_Clave_Mongo"
    restart: always
  app:
    container_name: python
    hostname: python
    depends_on:
      - db-sql
      - db-no-sql
    build: .
    ports:
      - "8888:8888"
    volumes:
      - C:/Users/Ema/Desktop/Cursos/SQL_Server_Docker/Files/01 Sql Server:/tf
    restart: always



    #./opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Mi_Super_Mega_Clave_Sql_Server

    # ALTER DATABASE AdventureWorks2019 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    # DROP DATABASE AdventureWorks2019;

    #RESTORE DATABASE [AdventureWorks2019] FROM DISK = '/scripts/AdventureWorks2019.bak' WITH MOVE 'AdventureWorks2017' TO '/var/opt/mssql/data/AdventureWorks2019.mdf', MOVE 'AdventureWorks2017_log' TO '/var/opt/mssql/data/AdventureWorks2019_log.ldf', FILE = 1,  NOUNLOAD,  STATS = 5;
    